# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node-cli-example

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  azure-devops-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Node Version
        run: echo "Hello World"
      
      - name: list down file
        run: ls
      
  
  
